apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- simple-rollout.yaml
- simple-svc-active.yaml
- simple-svc-preview.yaml

images:
- name: asia.gcr.io/io203-101/simple
  newTag: 2.5